// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineTea.DAL.Model;

namespace OnlineTea.DAL.Migrations
{
    [DbContext(typeof(DBContextApplication))]
    [Migration("20211220074938_Anwar")]
    partial class Anwar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineTea.DAL.Model.AssociatedProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("associatedProviders");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssociatedProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Dname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("facilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedProviderId");

                    b.HasIndex("facilityId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssociatedProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedProviderId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssociatedProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("doctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedProviderId");

                    b.HasIndex("doctorId");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Doctor", b =>
                {
                    b.HasOne("OnlineTea.DAL.Model.AssociatedProvider", null)
                        .WithMany("doctors")
                        .HasForeignKey("AssociatedProviderId");

                    b.HasOne("OnlineTea.DAL.Model.Facility", "facility")
                        .WithMany("doctors")
                        .HasForeignKey("facilityId");

                    b.Navigation("facility");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Facility", b =>
                {
                    b.HasOne("OnlineTea.DAL.Model.AssociatedProvider", null)
                        .WithMany("facilities")
                        .HasForeignKey("AssociatedProviderId");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Location", b =>
                {
                    b.HasOne("OnlineTea.DAL.Model.AssociatedProvider", null)
                        .WithMany("locations")
                        .HasForeignKey("AssociatedProviderId");

                    b.HasOne("OnlineTea.DAL.Model.Doctor", "doctor")
                        .WithMany("locations")
                        .HasForeignKey("doctorId");

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.AssociatedProvider", b =>
                {
                    b.Navigation("doctors");

                    b.Navigation("facilities");

                    b.Navigation("locations");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Doctor", b =>
                {
                    b.Navigation("locations");
                });

            modelBuilder.Entity("OnlineTea.DAL.Model.Facility", b =>
                {
                    b.Navigation("doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
